name: airborne
description: Minimal aircraft management app for small groups
homepage: https://github.com/daniele-athome/airborne
issue_tracker: https://github.com/daniele-athome/airborne/issues
repository: https://github.com/daniele-athome/airborne.git

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.8.0+29

environment:
  sdk: ">=3.9.0 <4.0.0"

dependencies:
  adaptive_dialog: 2.5.0
  archive: 4.0.7
  auto_size_text: 3.0.0
  collection: 1.19.1
  cupertino_calendar_picker: 2.2.6
  cupertino_icons: 1.0.8
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_platform_widgets: 9.0.0
  # latest version of upstream project unstable
  fluttertoast: 8.2.13
  googleapis: 15.0.0
  googleapis_auth: 2.0.0
  http: 1.5.0
  # not ready yet: https://github.com/daniele-athome/airborne/issues/78
  infinite_scroll_pagination: 4.1.0
  intl: 0.20.2
  json_schema: 5.2.2
  logging: 1.3.0
  material_segmented_control: 5.0.1
  package_info_plus: 9.0.0
  path: 1.9.1
  path_provider: 2.1.5
  provider: 6.1.5+1
  shared_preferences: 2.5.3
  solar_calculator: 1.0.3
  syncfusion_flutter_calendar: 31.2.4
  syncfusion_localizations: 31.2.4
  syncfusion_flutter_core: 31.2.4
  timeline_tile: 2.0.0
  timezone: 0.10.1
  url_launcher: 6.3.2
  validators: 3.0.0

dev_dependencies:
  build_runner:
  flutter_driver:
    sdk: flutter
  flutter_lints: any
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  lint: any
  mockito: any
  nock: 1.2.3
  path_provider_platform_interface: any
  plugin_platform_interface: any
  pubspec_generator: any
  random_date: any
  screenshots:
    git:
      url: https://github.com/daniele-athome/screenshots.git
      ref: 25f91f1352492f334a6af4cef869917ed23855cd
  test: any

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # Generate localizations
  generate: true

  assets:
    - assets/images/
    - assets/aircraft.schema.json

  fonts:
    - family: MajorMonoDisplay
      fonts:
        - asset: fonts/MajorMonoDisplay-Regular.ttf

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
